#pragma once

enum SeatPositions
{
	SEAT_DRIVER = -1,
	SEAT_PASSENGER = 0,
	SEAT_BACKDRIVER = 1,
	SEAT_BACKPASSENGER = 2
};

enum WheelTypes
{
	WHEEL_TYPE_STOCK = -1,
	WHEEL_TYPE_SPORT,
	WHEEL_TYPE_MUSCLE,
	WHEEL_TYPE_LOWRIDER,
	WHEEL_TYPE_SUV,
	WHEEL_TYPE_OFFROAD,
	WHEEL_TYPE_TUNER,
	WHEEL_TYPE_BIKEWHEELS,
	WHEEL_TYPE_HIGHEND,
	WHEEL_TYPE_CHROME
};

enum TunerTypes
{
	WHEEL_TUNER_STOCK = -1,
	WHEEL_TUNER_COSMO,
	WHEEL_TUNER_SUPERMESH,
	WHEEL_TUNER_OUTSIDER,
	WHEEL_TUNER_ROLLAS,
	WHEEL_TUNER_DRIFFMEISTER,
	WHEEL_TUNER_SLICER,
	WHEEL_TUNER_ELQUATRO,
	WHEEL_TUNER_DUBBED,
	WHEEL_TUNER_FIVESTAR,
	WHEEL_TUNER_SLIDEWAYS,
	WHEEL_TUNER_APEX,
	WHEEL_TUNER_STANCEDEG,
	WHEEL_TUNER_COUNTERSTEER,
	WHEEL_TUNER_ENDOV1,
	WHEEL_TUNER_ENDOV2DISH,
	WHEEL_TUNER_GUPPEZ,
	WHEEL_TUNER_CHOKADORI,
	WHEEL_TUNER_CHICANE,
	WHEEL_TUNER_SAISOKU,
	WHEEL_TUNER_DISHEDEIGHT,
	WHEEL_TUNER_FUJIWARA,
	WHEEL_TUNER_ZOKUSHA,
	WHEEL_TUNER_BATTLEVLLL,
	WHEEL_TUNER_RALLYMASTER
};

enum HighEndWheels
{
	WHEEL_HIGHEND_STOCK = -1,
	WHEEL_HIGHEND_SHADOW,
	WHEEL_HIGHEND_HYPHER,
	WHEEL_HIGHEND_BLADE,
	WHEEL_HIGHEND_DIAMOND,
	WHEEL_HIGHEND_SUPAGEE,
	WHEEL_HIGHEND_CHROMATICZ,
	WHEEL_HIGHEND_MERCIECHLIP,
	WHEEL_HIGHEND_OBEYRS,
	WHEEL_HIGHEND_GTCHROME,
	WHEEL_HIGHEND_CHEETAHR,
	WHEEL_HIGHEND_SOLAR,
	WHEEL_HIGHEND_SPLITTEN,
	WHEEL_HIGHEND_DASHVIP,
	WHEEL_HIGHEND_LOZSPEEDTEN,
	WHEEL_HIGHEND_CARBONINFERNO,
	WHEEL_HIGHEND_CARBONSHADOW,
	WHEEL_HIGHEND_CARBONZ,
	WHEEL_HIGHEND_CARBONSOLAR,
	WHEEL_HIGHEND_CARBONCHEETAHR,
	WHEEL_HIGHEND_CARBONSRACER
};

enum LowriderWheels
{
	WHEEL_LOWRIDER_STOCK = -1,
	WHEEL_LOWRIDER_FLARE,
	WHEEL_LOWRIDER_WIRED,
	WHEEL_LOWRIDER_TRIPLEGOLDS,
	WHEEL_LOWRIDER_BIGWORM,
	WHEEL_LOWRIDER_SEVENFIVES,
	WHEEL_LOWRIDER_SPLITSIX,
	WHEEL_LOWRIDER_FRESHMESH,
	WHEEL_LOWRIDER_LEADSLED,
	WHEEL_LOWRIDER_TURBINE,
	WHEEL_LOWRIDER_SUPERFIN,
	WHEEL_LOWRIDER_CLASSICROD,
	WHEEL_LOWRIDER_DOLLAR,
	WHEEL_LOWRIDER_DUKES,
	WHEEL_LOWRIDER_LOWFIVE,
	WHEEL_LOWRIDER_GOOCH,
};

enum MuscleWheels
{
	WHEEL_MUSCLE_STOCK = -1,
	WHEEL_MUSCLE_CLASSICFIVE,
	WHEEL_MUSCLE_DUKES,
	WHEEL_MUSCLE_MUSCLEFREAK,
	WHEEL_MUSCLE_KRACKA,
	WHEEL_MUSCLE_AZREA,
	WHEEL_MUSCLE_MECHA,
	WHEEL_MUSCLE_BLACKTOP,
	WHEEL_MUSCLE_DRAGSPL,
	WHEEL_MUSCLE_REVOLVER,
	WHEEL_MUSCLE_CLASSICROD,
	WHEEL_MUSCLE_FAIRLRE,
	WHEEL_MUSCLE_SPOONER,
	WHEEL_MUSCLE_FIVESTAR,
	WHEEL_MUSCLE_OLDSCHOOL,
	WHEEL_MUSCLE_ELJEFE,
	WHEEL_MUSCLE_DODMAN,
	WHEEL_MUSCLE_SIXGUN,
	WHEEL_MUSCLE_MERCENARY
};

enum OffroadWheels
{
	WHEEL_OFFROAD_STOCK = -1,
	WHEEL_OFFROAD_RAIDER,
	WHEEL_OFFROAD_MUDSLINGER,
	WHEEL_OFFROAD_NEVIS,
	WHEEL_OFFROAD_CAIRNGORM,
	WHEEL_OFFROAD_AMAZON,
	WHEEL_OFFROAD_CHALLENGER,
	WHEEL_OFFROAD_DUNEBASHER,
	WHEEL_OFFROAD_FIVESTAR,
	WHEEL_OFFROAD_ROCKCRAWLER,
	WHEEL_OFFROAD_MILSPECSTEELIE
};

enum SportWheels
{
	WHEEL_SPORT_STOCK = -1,
	WHEEL_SPORT_INFERNO,
	WHEEL_SPORT_DEEPFIVE,
	WHEEL_SPORT_LOZSPEED,
	WHEEL_SPORT_DIAMONDCUT,
	WHEEL_SPORT_CHRONO,
	WHEEL_SPORT_FEROCCIRR,
	WHEEL_SPORT_FIFTYNINE,
	WHEEL_SPORT_MERCIE,
	WHEEL_SPORT_SYNTHETICZ,
	WHEEL_SPORT_ORGANICTYPED,
	WHEEL_SPORT_ENDOV1,
	WHEEL_SPORT_DUPER7,
	WHEEL_SPORT_UZER,
	WHEEL_SPORT_GROUNDRIDE,
	WHEEL_SPORT_SRACER,
	WHEEL_SPORT_VENUM,
	WHEEL_SPORT_COSMO,
	WHEEL_SPORT_DASHVIP,
	WHEEL_SPORT_ICEKID,
	WHEEL_SPORT_RUFFWELD,
	WHEEL_SPORT_WANGENMASTER,
	WHEEL_SPORT_SUPERFIVE,
	WHEEL_SPORT_ENDOV2,
	WHEEL_SPORT_SLITSIX
};

enum SUVWheels
{
	WHEEL_SUV_STOCK = -1,
	WHEEL_SUV_VIP,
	WHEEL_SUV_BENEFACTOR,
	WHEEL_SUV_COSMO,
	WHEEL_SUV_BIPPU,
	WHEEL_SUV_ROYALSIX,
	WHEEL_SUV_FAGORME,
	WHEEL_SUV_DELUXE,
	WHEEL_SUV_ICEDOUT,
	WHEEL_SUV_COGNSCENTI,
	WHEEL_SUV_LOZSPEEDTEN,
	WHEEL_SUV_SUPERNOVA,
	WHEEL_SUV_OBEYRS,
	WHEEL_SUV_LOZSPEEDBALLER,
	WHEEL_SUV_EXTRAVAGANZO,
	WHEEL_SUV_SPLITSIX,
	WHEEL_SUV_EMPOWERED,
	WHEEL_SUV_SUNRISE,
	WHEEL_SUV_DASHVIP,
	WHEEL_SUV_CUTTER
};

enum BikeWheels
{
	WHEEL_BIKE_STOCK = -1,
	WHEEL_BIKE_SPEEDWAY,
	WHEEL_BIKE_STREETSPECIAL,
	WHEEL_BIKE_RACER,
	WHEEL_BIKE_TRACKSTAR,
	WHEEL_BIKE_OVERLORD,
	WHEEL_BIKE_TRIDENT,
	WHEEL_BIKE_TRIPLETHREAT,
	WHEEL_BIKE_STILLETO,
	WHEEL_BIKE_WIRES,
	WHEEL_BIKE_BOBBER,
	WHEEL_BIKE_SOLIDUS,
	WHEEL_BIKE_ICESHIELD,
	WHEEL_BIKE_LOOPS
};

enum VehicleModTypes
{
	MOD_SPOILER,
	MOD_FRONTBUMPER,
	MOD_REARBUMPER,
	MOD_SIDESKIRT,
	MOD_EXHAUST,
	MOD_CHASSIS, //Or roll cage
	MOD_GRILLE,
	MOD_HOOD,
	MOD_FENDER,
	MOD_RIGHTFENDER,
	MOD_ROOF,
	MOD_ENGINE,
	MOD_BRAKES,
	MOD_TRANSMISSION,
	MOD_HORNS,
	MOD_SUSPENSION,
	MOD_ARMOR,
	MOD_TURBO = 18,
	MOD_TIRESMOKE = 20,
	MOD_XENONLIGHTS = 22,
	MOD_FRONTWHEELS,
	MOD_BACKWHEELS //Bikes only
};

enum VehicleModHorns
{
	HORN_STOCK = -1,
	HORN_TRUCK,
	HORN_POLICE,
	HORN_CLOWN,
	HORN_MUSICAL1,
	HORN_MUSICAL2,
	HORN_MUSICAL3,
	HORN_MUSICAL4,
	HORN_MUSICAL5,
	HORN_SADTROMBONE,
	HORN_CALSSICAL1,
	HORN_CALSSICAL2,
	HORN_CALSSICAL3,
	HORN_CALSSICAL4,
	HORN_CALSSICAL5,
	HORN_CALSSICAL6,
	HORN_CALSSICAL7,
	HORN_SCALEDO,
	HORN_SCALERE,
	HORN_SCALEMI,
	HORN_SCALEFA,
	HORN_SCALESOL,
	HORN_SCALELA,
	HORN_SCALETI,
	HORN_SCALEDO_HIGH,
	HORN_JAZZ1,
	HORN_JAZZ2,
	HORN_JAZZ3,
	HORN_JAZZLOOP,
	HORN_STARSPANGBAN1,
	HORN_STARSPANGBAN2,
	HORN_STARSPANGBAN3,
	HORN_STARSPANGBAN4
};

enum VehicleAddonLevel
{
	MOD_INDEX_OFF = -1,
	MOD_INDEX_ONE, //To determine mod index, look at the mod menu in LSC, the first item is MOD_INDEX_ONE. Count down to the item you want. Stock counts as OFF.
	MOD_INDEX_TWO,
	MOD_INDEX_THREE,
	MOD_INDEX_FOUR,
	MOD_INDEX_FIVE,
	MOD_INDEX_SIX,
	MOD_INDEX_SEVEN,
	MOD_INDEX_EIGHT,
	MOD_INDEX_NINE
};

enum NeonLightLocations
{
	NEON_LEFT,
	NEON_RIGHT,
	NEON_FRONT,
	NEON_BACK
};

enum VehicleColorsChrome
{
	COLOR_CHROME = 120
};

enum VehicleColorsClassic
{
	COLOR_CLASSIC_BLACK = 0,
	COLOR_CLASSIC_GRAPHITE = 1,
	COLOR_CLASSIC_BLACK_STEEL = 2,
	COLOR_CLASSIC_DARK_STEEL = 3,
	COLOR_CLASSIC_SILVER = 4,
	COLOR_CLASSIC_BLUISH_SILVER = 5,
	COLOR_CLASSIC_ROLLED_STEEL = 6,
	COLOR_CLASSIC_SHADOW_SILVER = 7,
	COLOR_CLASSIC_STONE_SILVER = 8,
	COLOR_CLASSIC_MIDNIGHT_SILVER = 9,
	COLOR_CLASSIC_CAST_IRON_SILVER = 10,
	COLOR_CLASSIC_ANHRACITE_BLACK = 11,
	COLOR_CLASSIC_RED = 27,
	COLOR_CLASSIC_TORINO_RED = 28,
	COLOR_CLASSIC_FORMULA_RED = 29,
	COLOR_CLASSIC_BLAZE_RED = 30,
	COLOR_CLASSIC_GRACE_RED = 31,
	COLOR_CLASSIC_GARNET_RED = 32,
	COLOR_CLASSIC_SUNSET_RED = 33,
	COLOR_CLASSIC_CABERNET_RED = 34,
	COLOR_CLASSIC_CANDY_RED = 35,
	COLOR_CLASSIC_SUNRISE_ORANGE = 36,
	COLOR_CLASSIC_GOLD = 37,
	COLOR_CLASSIC_ORANGE = 38,
	COLOR_CLASSIC_DARK_GREEN = 49,
	COLOR_CLASSIC_RACING_GREEN = 50,
	COLOR_CLASSIC_SEA_GREEN = 51,
	COLOR_CLASSIC_OLIVE_GREEN = 52,
	COLOR_CLASSIC_BRIGHT_GREEN = 53,
	COLOR_CLASSIC_GASOLINE_GREEN = 54,
	COLOR_CLASSIC_PALE_DARK_GREEN = 56,
	COLOR_CLASSIC_MIDNIGHT_GREEN = 59,
	COLOR_CLASSIC_METALLIC_DARK_BLUE = 60,
	COLOR_CLASSIC_GALAXY_BLUE = 61,
	COLOR_CLASSIC_DARK_BLUE = 62,
	COLOR_CLASSIC_SAXON_BLUE = 63,
	COLOR_CLASSIC_BLUE = 64,
	COLOR_CLASSIC_MARINER_BLUE = 65,
	COLOR_CLASSIC_HARBOR_BLUE = 66,
	COLOR_CLASSIC_DIAMOND_BLUE = 67,
	COLOR_CLASSIC_SURF_BLUE = 68,
	COLOR_CLASSIC_NAUTICAL_BLUE = 69,
	COLOR_CLASSIC_ULTRA_BLUE = 70,
	COLOR_CLASSIC_SCHAFTER_PURPLE = 71,
	COLOR_CLASSIC_SPINNAKER_PURPLE = 72,
	COLOR_CLASSIC_RACING_BLUE = 73,
	COLOR_CLASSIC_LIGHT_BLUE = 74,
	COLOR_CLASSIC_SLATE_BLUE = 81,
	COLOR_CLASSIC_BABY_BLUE = 87,
	COLOR_CLASSIC_YELLOW = 88,
	COLOR_CLASSIC_RACE_YELLOW = 89,
	COLOR_CLASSIC_BRONZE = 90,
	COLOR_CLASSIC_DEW_YELLOW = 91,
	COLOR_CLASSIC_LIME_GREEN = 92,
	COLOR_CLASSIC_CHAMPAGNE = 93,
	COLOR_CLASSIC_FELTZER_BROWN = 94,
	COLOR_CLASSIC_CREEEN_BROWN = 95,
	COLOR_CLASSIC_CHOCOLATE_BROWN = 96,
	COLOR_CLASSIC_MAPLE_BROWN = 97,
	COLOR_CLASSIC_SADDLE_BROWN = 98,
	COLOR_CLASSIC_STRAW_BROWN = 99,
	COLOR_CLASSIC_MOSS_BROWN = 100,
	COLOR_CLASSIC_BISON_BROWN = 101,
	COLOR_CLASSIC_WOODBEECH_BROWN = 102,
	COLOR_CLASSIC_BEECHWOOD_BROWN = 103,
	COLOR_CLASSIC_SIENNA_BROWN = 104,
	COLOR_CLASSIC_SANDY_BROWN = 105,
	COLOR_CLASSIC_BLEACHED_BROWN = 106,
	COLOR_CLASSIC_CREAM = 107,
	COLOR_CLASSIC_ICE_WHITE = 111,
	COLOR_CLASSIC_FROST_WHITE = 112,
	COLOR_CLASSIC_DARK_BROWN = 115,
	COLOR_CLASSIC_PEA_GREEN = 125,
	COLOR_CLASSIC_POLICE_BLUE = 127,
	COLOR_CLASSIC_PURE_WHITE = 134,
	COLOR_CLASSIC_HOT_PINK = 135,
	COLOR_CLASSIC_SALMON_PINK = 136,
	COLOR_CLASSIC_PFSITER_PINK = 137,
	COLOR_CLASSIC_BRIGHT_ORANGE = 138,
	COLOR_CLASSIC_GREEN = 139,
	COLOR_CLASSIC_FLOURESCENT_BLUE = 140,
	COLOR_CLASSIC_MIDNIGHT_BLUE = 141,
	COLOR_CLASSIC_MIDNIGHT_PURPLE = 142,
	COLOR_CLASSIC_WINE_RED = 143,
	COLOR_CLASSIC_HUNTER_GREEN = 144,
	COLOR_CLASSIC_BRIGHT_PURPLE = 145,
	COLOR_CLASSIC_MIDNIGHT_GALAXY_BLUE = 146,
	COLOR_CLASSIC_CARBON_BLACK = 147,
	COLOR_CLASSIC_LAVA_RED = 150,
	COLOR_CLASSIC_EPSILON_BLUE = 157
};

enum VehicleColorsWorn
{
	COLOR_WORN_BLACK = 21,
	COLOR_WORN_GRAPHITE = 22,
	COLOR_WORN_SILVER_GREY = 23,
	COLOR_WORN_SILVER = 24,
	COLOR_WORN_BLUE_SILVER = 25,
	COLOR_WORN_SHADOW_SILVER = 26,
	COLOR_WORN_RED = 46,
	COLOR_WORN_GOLDEN_RED = 47,
	COLOR_WORN_DARK_RED = 48,
	COLOR_WORN_GREEN = 57,
	COLOR_WORN_SEA_WASH = 58,
	COLOR_WORN_DARK_BLUE = 85,
	COLOR_WORN_BLUE = 86,
	COLOR_WORN_HONEY_BEIGE = 113,
	COLOR_WORN_BROWN = 114,
	COLOR_WORN_STRAW_BEIGE = 116,
	COLOR_WORN_OFF_WHITE = 121,
	COLOR_WORN_ORANGE = 123,
	COLOR_WORN_LIGHT_ORANGE = 124,
	COLOR_WORN_TAXI_YELLOW = 126,
	COLOR_WORN_PALE_ORANGE = 130,
	COLOR_WORN_WHITE = 132,
	COLOR_WORN_ARMY_OLIVE_GREEN = 133
};

enum VehicleColorsUtil
{
	COLOR_UTIL_BLACK = 15,
	COLOR_UTIL_BLACK_POLY = 16,
	COLOR_UTIL_DARK_SILVER = 17,
	COLOR_UTIL_GUN_METAL = 19,
	COLOR_UTIL_SHADOW_SILVER = 20,
	COLOR_UTIL_RED = 43,
	COLOR_UTIL_BRIGHT_RED = 44,
	COLOR_UTIL_GARNET_RED = 45,
	COLOR_UTIL_MIDNIGHT_BLUE = 75,
	COLOR_UTIL_BLUE = 76,
	COLOR_UTIL_SEA_FOAM_BLUE = 77,
	COLOR_UTIL_LIGHTNING_BLUE = 78,
	COLOR_UTIL_MAUI_BLUE_POLY = 79,
	COLOR_UTIL_BRIGHT_BLUE = 80,
	COLOR_UTIL_BROWN = 108,
	COLOR_UTIL_MEDIUM_BROWN = 109,
	COLOR_UTIL_LIGHT_BROWN = 110,
	COLOR_UTIL_OFF_WHITE = 122
};

enum VehicleColorsMatte
{
	COLOR_MATTE_BLACK = 12,
	COLOR_MATTE_GRAY = 13,
	COLOR_MATTE_LIGHT_GRAY = 14,
	COLOR_MATTE_RED = 39,
	COLOR_MATTE_DARK_RED = 40,
	COLOR_MATTE_ORANGE = 41,
	COLOR_MATTE_YELLOW = 42,
	COLOR_MATTE_LIME_GREEN = 55,
	COLOR_MATTE_DARK_BLUE = 82,
	COLOR_MATTE_BLUE = 83,
	COLOR_MATTE_MIDNIGHT_BLUE = 84,
	COLOR_MATTE_GREEN = 128,
	COLOR_MATTE_BROWN = 129,
	COLOR_MATTE_ICE_WHITE = 131,
	COLOR_MATTE_SCHAFTER_PURPLE = 148,
	COLOR_MATTE_MIDNIGHT_PURPLE = 149,
	COLOR_MATTE_FOREST_GREEN = 151,
	COLOR_MATTE_OLIVE_DRAB = 152,
	COLOR_MATTE_DARK_EARTH = 153,
	COLOR_MATTE_DESERT_TAN = 154,
	COLOR_MATTE_FOLIAGE_GREEN = 155
};

enum VehicleColorsMetals
{
	COLOR_METALS_PEARLESCENT_STEEL = 18,
	COLOR_METALS_BRUSHED_STEEL = 117,
	COLOR_METALS_BRUSHED_BLACK_STEEL = 118,
	COLOR_METALS_BRUSHED_ALUMINUM = 119,
	COLOR_METALS_DEFAULT_ALLOY = 156,
	COLOR_METALS_PURE_GOLD = 158,
	COLOR_METALS_BRUSHED_GOLD = 159,
	COLOR_METALS_PEARLESCENT_GOLD = 160
};

enum PlateTypes
{
	PLATE_BLUEONWHITE1,
	PLATE_YELLOWONBLACK,
	PLATE_YELLOWONBLUE,
	PLATE_BLUEONWHITE2,
	PLATE_BLUEONWHITE3,
	PLATE_YANKTON
};

enum WindowTints //m8 do you even int tint?
{
	WINDOWTINT_NONE,
	WINDOWTINT_BLACK,
	WINDOWTINT_DARKSMOKE,
	WINDOWTINT_LIGHTSMOKE,
	WINDOWTINT_STOCK,
	WINDOWTINT_LIMO,
	WINDOWTINT_GREEN
};

#define NEON_COLOR_WHITE 222, 222, 255
#define NEON_COLOR_BLUE 2, 21, 255
#define NEON_COLOR_ELECTRICBLUE 3, 83, 255
#define NEON_COLOR_MINTGREEN 0, 255, 140
#define NEON_COLOR_LIMEGREEN 94, 255, 1
#define NEON_COLOR_YELLOW 255, 255, 0
#define NEON_COLOR_GOLDENSHOWER 255, 150, 5
#define NEON_COLOR_ORANGE 255, 62, 0
#define NEON_COLOR_RED 255, 1, 1
#define NEON_COLOR_PONYPINK 255, 50, 100 //Fag
#define NEON_COLOR_HOTPINK 255, 5, 190
#define NEON_COLOR_PURPLE 35, 1, 255
#define NEON_COLOR_BACKLIGHT 15, 3, 255

#define TIRESMOKE_COLOR_WHITE 255, 255, 255
#define TIRESMOKE_COLOR_BLACK 20, 20, 20
#define TIRESMOKE_COLOR_BLUE 0, 174, 239
#define TIRESMOKE_COLOR_YELLOW 252, 238, 0
#define TIRESMOKE_COLOR_PURPLE 100, 79, 142
#define TIRESMOKE_COLOR_ORANGE 255, 127, 0
#define TIRESMOKE_COLOR_GREEN 114, 204, 114
#define TIRESMOKE_COLOR_RED 226, 6, 6
#define TIRESMOKE_COLOR_PINK 203, 54, 148
#define TIRESMOKE_COLOR_BROWN 180, 130, 97
#define TIRESMOKE_COLOR_PATRIOT 0, 0, 0
#define TIRESMOKE_COLOR_MERRYWEATHER_MESA 21, 51, 66